### ISSUE TITLE
Do not install the plugin

### ISSUE THREAD

**Issue by zaval1976** [reevoo/fluent-plugin-systemd#85]
Hello,

I'm trying install plugin on CentOS7:
# cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)

See an error:
[root@kbn-wn-01 log]# gem install fluent-plugin-systemd -v 1.0.2
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-systemd:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
checking for ruby/st.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib64
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/ruby
/usr/share/ruby/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/share/ruby/mkmf.rb:565:in `try_cpp'
        from /usr/share/ruby/mkmf.rb:1038:in `block in have_header'
        from /usr/share/ruby/mkmf.rb:889:in `block in checking_for'
        from /usr/share/ruby/mkmf.rb:340:in `block (2 levels) in postpone'
        from /usr/share/ruby/mkmf.rb:310:in `open'
        from /usr/share/ruby/mkmf.rb:340:in `block in postpone'
        from /usr/share/ruby/mkmf.rb:310:in `open'
        from /usr/share/ruby/mkmf.rb:336:in `postpone'
        from /usr/share/ruby/mkmf.rb:888:in `checking_for'
        from /usr/share/ruby/mkmf.rb:1037:in `have_header'
        from extconf.rb:3:in `<main>'

Gem files will remain installed in /usr/local/share/gems/gems/msgpack-1.3.3 for inspection.
Results logged to /usr/local/share/gems/gems/msgpack-1.3.3/ext/msgpack/gem_make.out

The mkmf.log
"gcc -o conftest -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.    -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -mtune=generic -fPIC conftest.c  -L. -L/usr/lib64 -L. -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic  -m64   -lruby  -lpthread -lrt -ldl -lcrypt -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

Please, help.

**Comment by zaval1976** [comment]
Sorry, I'm solved the problem. Was not install GCC.
